name: PullRequest

on:
  pull_request:
    branches: [master]

jobs:
  build:
    name: Preview
    runs-on: [self-hosted, linux, x64, shared]
    steps:
      - name: Setup
        uses: whywhy36/crafting-sandbox-action/@v0.0.1
        with:
          name:
      - name: Build and Test
        run: .github/workflows/build_and_test.sh
