name: PullRequest

on:
  pull_request:
    branches: [master]

jobs:
  build:
    name: Preview
    runs-on: [ubuntu-latest]
    env:
      ACTIONS_RUNNER_DEBUG: true
    steps:
      - uses: actions/checkout@v2
      - name: Setup
        id: generateurl
        uses: whywhy36/crafting-sandbox-action/@v0.0.6
        with:
          name: hello
      - name: Create PR comment
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { owner, repo } = context.repo;
            const { number } = context.payload.pull_request;
            const message = 'Crafting Sandbox Preview Sandbox: ${{ steps.generateurl.outputs.url }}';

            const octokit = new github.GitHub(process.env.GITHUB_TOKEN);
            octokit.issues.createComment({ owner, repo, issue_number: number, body: message });
