name: PullRequest

on:
  pull_request:
    branches: [master]

jobs:
  build:
    name: Preview
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Setup
        uses: whywhy36/crafting-sandbox-action/@v0.0.3
        with:
          name: hello
