name: PullRequest

on:
  pull_request:
    branches: [master]

jobs:
  build:
    name: Preview
    runs-on: [ubuntu]
    steps:
      - name: Setup
        uses: whywhy36/crafting-sandbox-action/@v0.0.1
        with:
          name: hello
